// Auto-generated by ACL-ADLC Figma Asset Pipeline (Layer 2)
// Do not edit manually

import user1Icon from './user1.svg';
import user2Icon from './user2.svg';
import herobannerimageImg from './herobannerimage.png';

export const FigmaAssets = {
  user1Icon,
  user2Icon,
  herobannerimageImg,
};

export default FigmaAssets;